###########################
# Circuitman Config       #
# Written by boyninja1555 #
###########################

#################
# Chat messages #
#################
admin:
    reloaded: <yellow>[ᴄɪʀᴄᴜɪᴛᴍᴀɴ]<gold> ʀᴇʟᴏᴀᴅᴇᴅ
    config-regenerated: <yellow>[ᴄɪʀᴄᴜɪᴛᴍᴀɴ]<gold> ᴄᴏɴꜰɪɢ.ʏᴍʟ ʀᴇɢᴇɴᴇʀᴀᴛᴇᴅ
    config-not-regenerated: <red>[ᴄɪʀᴄᴜɪᴛᴍᴀɴ]<dark_red> ᴄᴏɴꜰɪɢ.ʏᴍʟ ɴᴏᴛ ʀᴇɢᴇɴᴇʀᴀᴛᴇᴅ! ᴄʜᴇᴄᴋ ᴛʜᴇ ᴄᴏɴꜱᴏʟᴇ ꜰᴏʀ ᴇʀʀᴏʀꜱ

######################
# Flammable redstone #
######################

# Burn time per wire
# There are 20 ticks in a second
redstone-burn-time: 5  # 0.25 seconds

# Amount of flames per burning wire
redstone-flame-count: 5

# This is used when burning redstone hits a TNT block
# It is like the `/summon tnt` command's `power` argument
redstone-tnt-explode-power: 25

# Whether fire should appear when burning redstone hits a TNT block
redstone-tnt-explode-fire: true

# WARNING: ADVANCED & DANGEROUS
# This field prevents lag by capping the amount of times a flame can burn wires
# Do not change this unless you're sure the server is beefy enough!
redstone-burn-depth: 25

########################################
# Circuitman Experimental Config       #
# Written by boyninja1555              #
#                                      #
# WARNING: ADVANCED AND DANGEROUS      #
# When set to true, it forces the      #
# values below, which are SUPER        #
# experimental and not officially      #
# supported! They may crash the server #
# for zero reason AT ALL:              #
#                                      #
# redstone-burn-time: 2  # 0.1 seconds #
# redstone-flame-count: 10             #
# redstone-tnt-explode-power: 45       #
# redstone-tnt-explode-fire: true      #
# redstone-burn-depth: 100             #
########################################
experimental-mode: false